[tool.black]
line-length = 80
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git     # exclude the ".git" directory
  | \.github  # exclude the ".github" directory
  | \.pytest_cache # exclude the ".pytest_cache" directory
  | venv    # exclude the ".venv" directory
  | \.idea    # exclude the "idea" directory 
  | __pycache__ # exclude "pycache" directory
  | .*egg-info
)/
'''

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 80
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
